import os, sys, argparse

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import repop
import torch
import numpy as np

from utils.load_and_clean_real_data import load_and_pool_real_data
from repop.utils import Igaussmix_loglike


# --- Mixture postprocessing: keep only rightmost components ---
def get_rightmost_components_from_dt(dt, top_n=4, renormalize=True):
    m, s, r = dt.ev
    idx = torch.argsort(m)

    if len(r) < top_n:
        raise ValueError(f"Only {len(r)} components available (requested top_n={top_n}).")

    idx = idx[-top_n:]
    mN, sN, rN = m[idx], s[idx], r[idx]

    if renormalize:
        rN = rN / rN.sum()

    return mN, sN, rN


def reconstruct_top_components(dt, top_n=4, narray=None, cpu=True, **kwargs):
    if narray is None:
        x = dt.n
    else:
        x = narray * 1.0

    m, s, r = get_rightmost_components_from_dt(dt, top_n=top_n, **kwargs)
    p = torch.exp(Igaussmix_loglike(x, m, s, r))

    if cpu:
        x, p = x.cpu(), p.cpu()

    return x, p


def parse_args():
    p = argparse.ArgumentParser(
        description="Calibrate capacity (kappa) distribution from Day X plate-count data using REPOP."
    )
    p.add_argument(
        "--datapaths",
        nargs="+",
        required=True,
        help="One or more CSV paths (e.g., real_data/Exp_4_live_highpH.csv).",
    )
    p.add_argument("--day", type=int, default=9, help="Day to filter on (default: 9).")
    p.add_argument("--cutoff", type=int, default=300, help="Count cutoff (default: 300).")
    p.add_argument("--top-n", type=int, default=4, help="Number of rightmost Gaussians to keep (default: 4).")
    p.add_argument(
        "--out",
        type=str,
        default=None,
        help="Output .npz path. If omitted, a name is autogenerated.",
    )
    p.add_argument("--no-renorm", action="store_true", help="Do not renormalize weights after truncation.")
    p.add_argument("--verbose", action="store_true", help="Verbose data loading output.")
    return p.parse_args()


def run_calibration(datapaths, day=9, cutoff=300, top_n=4, out=None, renormalize=True, verbose=False):
    # Load data from only Day day from selected real data CSVs
    df_day = load_and_pool_real_data(
        filepaths=datapaths,
        days=day,
        cutoff=cutoff,
        verbose=verbose,
    )

    if len(df_day) == 0:
        raise ValueError(f"No Day {day} rows after filtering/cleaning for datapaths={datapaths}")

    counts = df_day["Counts"].to_numpy()
    dils   = df_day["Dilution"].to_numpy()

    # Run REPOP on Day data to extract p(K)
    dt = repop.dataset(counts=counts, dils=dils, cutoff=cutoff)

    # Fit mixture
    dt.evaluate(components=repop.weak_limit, observe=True, component_cut=0)

    # Reconstruct capacity distribution from rightmost components
    x, p = reconstruct_top_components(
        dt,
        top_n=top_n,
        cpu=True,
        renormalize=renormalize,
    )

    x = x.reshape(-1).detach().cpu().numpy()
    p = p.reshape(-1).detach().cpu().numpy()
    p = p / p.sum()

    if out is None:
        base = "_".join(os.path.splitext(os.path.basename(fp))[0] for fp in datapaths)
        out = f"capacity_day{day}_repop_top{top_n}_{base}.npz"

    np.savez(out, kappa=x, p=p)
    return out


def main():
    args = parse_args()
    out = run_calibration(
        datapaths=args.datapaths,
        day=args.day,
        cutoff=args.cutoff,
        top_n=args.top_n,
        out=args.out,
        renormalize=(not args.no_renorm),
        verbose=args.verbose,
    )
    print(f"Saved capacity calibration to: {out}")


if __name__ == "__main__":
    main()